### ISSUE TITLE
No add/remove handles in edit mode on iOS build

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#22]
In the iOS build you don't see the small coloured dots in edit mode e.g. https://i.imgur.com/1qk8e0w.png

**Comment by hosseinamin** [comment]
hopefully fixed. i fixed other bugs in the way....

**Comment by willwade** [comment]
Nearly there.. The white border is coming up but still not seeing the red/green add/remove handle :(

![screen shot 2017-07-31 at 11 43 20](https://user-images.githubusercontent.com/229352/28774496-9825d7da-75e5-11e7-830d-ccdd259a544e.png)

**Comment by hosseinamin** [comment]
I did add bootstrap glyphicons to pasco-cordova project. It should get fixed after that.

**Comment by willwade** [comment]
Fixed!
